### ISSUE TITLE
Feat - Primary Keys in some Models.

### ISSUE THREAD

**Issue by Fraser-Levack** [Team-2D/GameScoreCentral#1]
# Default Primary Keys #

## Hi I'm Fraser.

I've been testing your application and believe I have information that might help:

Due to the way migrations work with Django some of your models may benefit  to have a default primary key state. This could be implemented by adding in this line to make a new auto primary key field.
~~~
custom_id = models.AutoField(primary_key=True)
~~~

I believe this may work best for you game models as duplicate game entries may result in errors. 

## Hope this helps and you can resolve this easily !
# 🐱‍💻

**Comment by lewistough04** [comment]
Django automatically adds an id field to each model
